#build openal-soft on linux/macos
name: build
on:
  release:
    types:
      - created
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  #job to build openal-soft on linux x86-64
  build-linux-x86-64:
    name: build-linux-x86-64
    runs-on: ubuntu-latest
    steps:
      #checkout submodules
      - uses: actions/checkout@v1
        with: 
          submodules: true
      - name: Build openal-soft
        run: |
          cd openal-soft
          cd build
          cmake ..
          make -j4 OpenAL
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
      # upload release to github
      - name: Upload
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: openal-soft/build/libopenal.so
          asset_name: libopenal-linux-x86_64.so
          asset_content_type: application/octet-stream
  #job to build openal-soft on macos x86-64
  build-macos-x86-64:
    name: build-macos-x86-64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with: 
          submodules: true
      - name: Build openal-soft
        run: |
          cd openal-soft
          cd build
          cmake ..
          make -j4 OpenAL
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
      # upload release to github
      - name: Upload
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: openal-soft/build/libopenal.dylib
          asset_name: libopenal-macos-x86_64.dylib
          asset_content_type: application/octet-stream
  #job to build openal-soft on linux arm64
  build-linux-arm64:
    name: build-linux-arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with: 
          submodules: true
      - name: Build openal-soft
        run: |
          cd openal-soft
          cd build
          cmake ..
          make -j4 OpenAL
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
      # upload release to github
      - name: Upload
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: openal-soft/build/libopenal.so
          asset_name: libopenal-linux-arm64.so
          asset_content_type: application/octet-stream
  #job to cross compile openal-soft for macos arm64
  cross-compile-macos-arm64:
    name: cross-compile-macos-arm64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with: 
          submodules: true
      #apply macos arm64 patch
      - name: Apply patch
        run: |
          cd openal-soft
          patch -p1 < ../macos-arm64.patch
      - name: Build openal-soft
        run: |
          cd openal-soft
          cd build
          cmake ..
          make -j4 OpenAL
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
      # upload release to github
      - name: Upload
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: openal-soft/build/libopenal.dylib
          asset_name: libopenal-macos-arm64.dylib
          asset_content_type: application/octet-stream